# Generated by Django 4.1.13 on 2024-10-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recent',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
